version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4551:4551
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27015:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
